### PR TITLE
Use Restrictive Permissions for Stack creation and service operations

### PR DESCRIPTION
**Pull request by rajeevr2715**
**Requirements**

In order to keep the permissions restrictive for the stack admin,

* Remove the IAM create User and Create policy, attach policy permissions from Stack Admin. ie Remove the operational user created for service operations. so that only a single admin user will be there to handle the service operations
* Refactor the stack admin permission with less level of permission and restrictions on resources

### CODE REVIEW

**Comment by rajeevr2715** [comment]
@bleggett terraform will update the keys value in the variables, only if we set the env as , 

> export AWS_ACCESS_KEY_ID=<YOUR_ACCESS_KEY>
> export AWS_SECRET_ACCESS_KEY=<YOUR_SECRET_KEY>

and pass the keys as environment variables

> like , tfCommand = [
>             'terraform', 'apply', '--auto-approve',
>             '-var', 'aws_access_key=${AWS_ACCESS_KEY_ID}'
>             '-var', 'aws_access_key=%s' %(os.environ['AWS_ACCESS_KEY_ID']),
>             '-var', 'aws_secret_key=%s' %(os.environ['AWS_SECRET_ACCESS_KEY'])

If the user has not entered env, then we should either ask for user inputs or read the default profile as keys. Earlier this was handled by asking user input for keys, https://github.com/rajeevr2715/jazz-installer/blob/84d0e9d001d1f7b8f536818e772f665c744636cf/installscripts/wizard/scenarios/jazz_generic_details.py#L38

can we use the same approach here as well?

**Comment by bleggett** [comment]
> @bleggett terraform will update the keys value in the variables(${var.aws_access_key}), only if we set the env as ,
> 
> > export AWS_ACCESS_KEY_ID=<YOUR_ACCESS_KEY>
> > export AWS_SECRET_ACCESS_KEY=<YOUR_SECRET_KEY>
> 
> and pass the keys as environment variables
> 
> > like , tfCommand = [
> > 'terraform', 'apply', '--auto-approve',
> > '-var', 'aws_access_key=${AWS_ACCESS_KEY_ID}'
> > '-var', 'aws_access_key=%s' %(os.environ['AWS_ACCESS_KEY_ID']),
> > '-var', 'aws_secret_key=%s' %(os.environ['AWS_SECRET_ACCESS_KEY'])
> 
> If the user has not entered env, then we should either ask for user inputs or read the default profile and fetch the keys in order to get the keys from variables (${var.aws_access_key}). Earlier this was handled by asking user input for keys,
> 
> https://github.com/tmobile/jazz-installer/blob/84d0e9d001d1f7b8f536818e772f665c744636cf/installscripts/wizard/scenarios/jazz_generic_details.py#L38
> 
> can we use the same approach here as well?

`terraform` will pick up AWS auth config previously generated by running `aws configure`, we don't really need to reinvent the wheel there for interactive installs, just document that people run that command first, if they're working **interactively** with AWS they should do that anyway.

For noninteractive/automated installs, we should be putting that stuff in env vars anyway.

So no, I don't see any real value add in adding prompts for those to our installer. Just let's document the above, since they're kinda no-brainers.

**Comment by rajeevr2715** [comment]
Agree. The best way would be using the env variables. Requirement is we need to keep only one IAM user in the jazz application ie both stack admin and platform operational user will be same. The reason is we need to remove the risky IAM user permissions from the stack admin. 

So we need to pass the aws_access_key and aws_secret_key values into the Configure Jenkins script. Terraform will update the variables -  aws_access_key and aws_secret_key only when we use ENV. Even if we set the aws configure without ENV, then terraform wont update the variable values.

**Comment by rajeevr2715** [comment]
@bleggett Updated code to handle interactive scenario to map the env using Click. https://github.com/tmobile/jazz-installer/pull/548/commits/cee3f8e41c4632b9dd3eaad0648c0db5c44a1c92

**Comment by raghits** [comment]
LGTM.

**Pull request merged**
