### PR TITLE
Adding support for Docker builds, K-native installation, container registry configuration

### PR DESCRIPTION
**Pull request by Deepak-Babu**
Adding support for Docker builds, K-native installation, container registry configuration

### CODE REVIEW

**Comment by bleggett** [comment]
Hey Deepak, thanks for taking a look at this.

From a cursory look, I take it this assumes you have a preexisting Knative install in GCP? 

A few things: 

- We're very close to finishing a rework of how the installer works, and removing explicit Docker support (see the `jenkins_docker` branch). 

- We're also following a specific feature extension structure for optional features (see `feature-extensions/splunk` for instance, or `feature-extensions/apigee` in the `apigee-extension` branch for a more complex example)

- We're also not accepting any significant new code written as a shell script, for maintenance reasons new installer code should be either Terraform or Python(2) to be accepted.

- It seems like you're installing the Docker CE runtime inside of the Jenkins Docker image itself (and using sock passthru)? This will not work with the upcoming changes, as we are moving to ECS and dropping the requirement for a local, addressable Docker runtime (and do not plan to support that in the future, or at least accept any code that assumes an ambient Docker runtime is available)

- It looks like you are assuming the scripts (e.g. `knative-installer.sh`) will be run on a Debian variant?

**Comment by devsatishm** [comment]
> * feature

@bleggett  Yes, this is related to `knative-plugin` branch.

@Deepak-Babu there were lot of new changes at the installer side (for good!) that might force you to refactor your code. Let's chat about this offline on next steps.

**Comment by devsatishm** [comment]
> * We have a `knative-plugin` branch, @suryajak or @devsatishm is this related to that effort at all?

@bleggett Yes, this is related to `knative-plugin` branch.

@Deepak-Babu there were lot of new changes at the installer side (for good!) that might force you to refactor your code. Let's chat about this offline on next steps.

**Comment by Deepak-Babu** [comment]
> > * We have a `knative-plugin` branch, @suryajak or @devsatishm is this related to that effort at all?
> 
> @bleggett Yes, this is related to `knative-plugin` branch.
> 
> @Deepak-Babu there were lot of new changes at the installer side (for good!) that might force you to refactor your code. Let's chat about this offline on next steps.



> Hey Deepak, thanks for taking a look at this.
> 
> From a cursory look, I take it this assumes you have a preexisting Knative install in GCP?
> 
> Is there a publicly-visible feature request for this effort somewhere?
> 
> A few things:
> 
> * We're very close to finishing a rework of how the installer works, and removing explicit Docker support (see the `jenkins_docker` branch), at this point I would ask that a change this significant be started from that baseline and not `master`, and probably tested and merged into a feature branch first.
> * We're also following a specific feature extension structure for optional features (see `feature-extensions/splunk` for instance, or `feature-extensions/apigee` in the `apigee-extension` branch for a more complex example). If that's what you're going for I would ask that you rework your contribution to mimic that convention.
> * We're also not accepting any significant new code written as shell scripts, for maintenance reasons new installer (or feature extension) code should be either Terraform or Python(2, soon 3).
> * It seems like you're installing the Docker CE runtime inside of the Jenkins Docker image itself (and using sock passthru)? This will not work with the upcoming changes, as we are moving to ECS and dropping the requirement for a local, addressable Docker runtime (and do not plan to support that in the future, or at least accept any code that assumes an ambient Docker runtime is available). This seems like a "just because you can doesn't mean you should" situation, won't Knative support in-cluster builds with Buildah quite soon, thereby removing the need for this anyway?
> * It looks like you are assuming the scripts (e.g. `knative-installer.sh`) will be run on a Debian variant?
> * We have a `knative-plugin` branch, @suryajak or @devsatishm is this related to that effort at all?

@bleggett @devsatishm thanks for taking a look, I'll review the comments and connect offline. I've had this for a while and have not done a PR. I can take a look at what's changed on the installer for sure.

Just a few clarifications:

- We're very close to finishing a rework of how the installer works, and removing explicit Docker support 
I guess I have to understand how you are planning to do docker builds on Jazz because K-Native will need it 

- It looks like you are assuming the scripts (e.g. knative-installer.sh) will be run on a Debian variant?
Yes because these were planned to be executed in the build environment (Jenkins OSS) which is a Debian container. I believe you only get Debian version of Jenkins Open source

**Comment by bleggett** [comment]
We will not ever do Docker builds *in* Jazz, because we don't need to.

https://github.com/knative/build/ is what we will eventually use, because that will (eventually) let you build the function containers in-cluster with Knative, which is the only really useful endgame for anything in the Knative ecosystem anyway, if you have to build and publish the containers yourself Knative offers almost zero value over naked Kube and is more or less just a toy.

Which is why they're working hard on implementing knative/build on top of Buildah. Once that work is done this will become a moot point.

**Pull request closed without merging**
