### PR TITLE
Removing unused permissions from IAM role that gets created as part of stack creation

### PR DESCRIPTION
**Pull request by devsatishm**
Changes to remove unwanted permissions from role that gets created as part of stack creation - Granting Least Privilege.

### CODE REVIEW

**Comment by bleggett** [comment]
This is great and LGTM - but what's it got to do with `events`? This looks like a standalone change we could test and push separately to `master` rather than bundle up with `events` and wait for that large merge to happen.

**Comment by bleggett** [comment]
Helps with #308 (tagging for reference purposes)

**Comment by devsatishm** [comment]
@bleggett  Agreed, it can go in directly (patch) but I thought going through the standard workflow might be better too that we can validate the changes as part of daily stack validator.

**Comment by suryajak** [comment]
This PR would have made sense to come in as an independent branch as its a security patch (a few more are on their way). Are we pushing them into events because we don't have a daily stack of our own and are currently running on a loaned AWS account?

**Comment by bleggett** [comment]
I'm OK with retargeting this on `master`, merging it, and pulling current `master` into `events`

**Pull request merged**
