### PR TITLE
Fix npm install errors

### PR DESCRIPTION
**Pull request by bleggett**
Stopgap fix for #396 

Current master is essentially broken, this is fixed in the `jenkins_docker` branch but because of how we favor long-running feature branches the fix never made its way back into `master` because that feature is not yet done (one could argue the current release should not have gone out as well, clearly it wasn't tested).

Issue: Normally, `npm` will purposefully fail if you run as a `root` user without `sudo`, which is good practice generally. However, when building a docker container, we are running as root by necessity, and do not care. The `--unsafe` param lets us bypass this check, and the install of `serverless` succeeds.

Also backported fixes around provisioning script bugs that have been fixed in `jenkins_docker`

### CODE REVIEW

**Comment by bleggett** [comment]
The CI checks are failing on `centos7-provision.sh` issues, since that script is already fixed in a feature branch and I am merely touching it to backport fixes, I am going to ignore those failures on this branch for now.

**Comment by suryajak** [comment]
@bleggett : `master` was validated where we have two running instances that were built before the release went out. @rajeevr2715 can you confirm if you used the same command as listed on our wiki: https://github.com/tmobile/jazz-installer/wiki#install?

**Comment by bleggett** [comment]
@suryajak It definitely fixes the failure to installer the `serverless` NPM package jenkins-side.

Without this that install fails. The installer continues, because that is being installed inside a docker container during a Docker build and the return code isn't checked.

Which means that any test using scenario 1 wouldn't catch this, because `serverless` would already exist on the Jenkins box. Do we actually test for the successful deploy of functions with scenario3?

**Comment by suryajak** [comment]
@bleggett : The two instances that we have currently running were built using scenario 3. Our daily installer uses scenario (1) while a separate adhoc build job validates scenario (3). @rajeevr2715: Please confirm if the two stacks that you built (scenario 3) worked without any manual fixes.

**Comment by bleggett** [comment]
```
Removing intermediate container 7d42d26afc5c
 ---> ebf7b33cf374
Step 6/16 : RUN curl -sL https://deb.nodesource.com/setup_8.x | bash && apt-get install -y nodejs && npm install  -global serverless@1.30.0 @angular/cli@1.7.3 jshint
 ---> Running in d8eaf577ddb8

## Installing the NodeSource Node.js 8.x LTS Carbon repo...


## Populating apt-get cache...

+ apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Reading package lists...

## Installing packages required for setup: apt-transport-https...

+ apt-get install -y apt-transport-https > /dev/null 2>&1

## Confirming "stretch" is supported...

+ curl -sLf -o /dev/null 'https://deb.nodesource.com/node_8.x/dists/stretch/Release'

## Adding the NodeSource signing key to your keyring...

+ curl -s https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
Warning: apt-key output should not be parsed (stdout is not a terminal)
OK

## Creating apt sources list file for the NodeSource Node.js 8.x LTS Carbon repo...

+ echo 'deb https://deb.nodesource.com/node_8.x stretch main' > /etc/apt/sources.list.d/nodesource.list
+ echo 'deb-src https://deb.nodesource.com/node_8.x stretch main' >> /etc/apt/sources.list.d/nodesource.list

## Running `apt-get update` for you...

+ apt-get update
Hit:1 http://security.debian.org/debian-security stretch/updates InRelease
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Get:5 https://deb.nodesource.com/node_8.x stretch InRelease [4647 B]
Get:7 https://deb.nodesource.com/node_8.x stretch/main Sources [762 B]
Get:8 https://deb.nodesource.com/node_8.x stretch/main amd64 Packages [1008 B]
Fetched 6417 B in 0s (9191 B/s)
Reading package lists...

## Run `sudo apt-get install -y nodejs` to install Node.js 8.x LTS Carbon and npm
## You may also need development tools to build native addons:
     sudo apt-get install gcc g++ make
## To install the Yarn package manager, run:
     curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
     echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
     sudo apt-get update && sudo apt-get install yarn


Reading package lists...
Building dependency tree...
Reading state information...
The following NEW packages will be installed:
  nodejs
0 upgraded, 1 newly installed, 0 to remove and 29 not upgraded.
Need to get 13.6 MB of archives.
After this operation, 64.2 MB of additional disk space will be used.
Get:1 https://deb.nodesource.com/node_8.x stretch/main amd64 nodejs amd64 8.14.0-1nodesource1 [13.6 MB]
debconf: delaying package configuration, since apt-utils is not installed
Fetched 13.6 MB in 0s (42.2 MB/s)
Selecting previously unselected package nodejs.
(Reading database ... 35852 files and directories currently installed.)
Preparing to unpack .../nodejs_8.14.0-1nodesource1_amd64.deb ...
Unpacking nodejs (8.14.0-1nodesource1) ...
Setting up nodejs (8.14.0-1nodesource1) ...
npm WARN deprecated browserslist@2.11.3: Browserslist 2 could fail on reading Browserslist >3.0 config used in other tools.
npm WARN deprecated boom@2.10.1: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated cryptiles@2.0.5: This version is no longer maintained. Please upgrade to the latest version.
npm WARN deprecated hoek@2.16.3: This version is no longer maintained. Please upgrade to the latest version.
/usr/bin/ng -> /usr/lib/node_modules/@angular/cli/bin/ng
/usr/bin/jshint -> /usr/lib/node_modules/jshint/bin/jshint
/usr/bin/serverless -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/slss -> /usr/lib/node_modules/serverless/bin/serverless
/usr/bin/sls -> /usr/lib/node_modules/serverless/bin/serverless

> phantomjs-prebuilt@2.1.16 install /usr/lib/node_modules/jshint/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Downloading https://github.com/Medium/phantomjs/releases/download/v2.1.1/phantomjs-2.1.1-linux-x86_64.tar.bz2
Saving to /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2
Receiving...

Received 22866K total.
Extracting tar contents (via spawned process)
Removing /usr/lib/node_modules/jshint/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1543536916414/phantomjs-2.1.1-linux-x86_64 -> /usr/lib/node_modules/jshint/node_modules/phantomjs-prebuilt/lib/phantom
Phantom installation failed { Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1543536916414/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/jshint/node_modules/phantomjs-prebuilt/lib/phantom'
  errno: -13,
  code: 'EACCES',
  syscall: 'link',
  path: '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1543536916414/phantomjs-2.1.1-linux-x86_64',
  dest: '/usr/lib/node_modules/jshint/node_modules/phantomjs-prebuilt/lib/phantom' } Error: EACCES: permission denied, link '/tmp/phantomjs/phantomjs-2.1.1-linux-x86_64.tar.bz2-extract-1543536916414/phantomjs-2.1.1-linux-x86_64' -> '/usr/lib/node_modules/jshint/node_modules/phantomjs-prebuilt/lib/phantom'

> node-sass@4.10.0 install /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/install.js

Unable to save binary /usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor/linux-x64-57 : { Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor'
    at Object.fs.mkdirSync (fs.js:885:18)
    at sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:71:13)
    at Function.sync (/usr/lib/node_modules/@angular/cli/node_modules/mkdirp/index.js:77:24)
    at checkAndDownloadBinary (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:114:11)
    at Object.<anonymous> (/usr/lib/node_modules/@angular/cli/node_modules/node-sass/scripts/install.js:157:1)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
  errno: -13,
  code: 'EACCES',
  syscall: 'mkdir',
  path: '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/vendor' }

> uglifyjs-webpack-plugin@0.4.6 postinstall /usr/lib/node_modules/@angular/cli/node_modules/webpack/node_modules/uglifyjs-webpack-plugin
> node lib/post_install.js


> spawn-sync@1.0.15 postinstall /usr/lib/node_modules/serverless/node_modules/spawn-sync
> node postinstall


> node-sass@4.10.0 postinstall /usr/lib/node_modules/@angular/cli/node_modules/node-sass
> node scripts/build.js

Building: /usr/bin/node /usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.8.0
gyp info using node@8.14.0 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.13
gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
gyp verb get node dir no --target version specified, falling back to host node version: 8.14.0
gyp verb command install [ '8.14.0' ]
gyp verb install input version string "8.14.0"
gyp verb install installing version: 8.14.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp WARN EACCES user "undefined" does not have permission to access the dev dir "/root/.node-gyp/8.14.0"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp"
gyp verb tmpdir == cwd automatically will remove dev files after to save disk space
gyp verb command install [ '--node_gyp_internal_noretry', '8.14.0' ]
gyp verb install input version string "8.14.0"
gyp verb install installing version: 8.14.0
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version not already installed, continuing with install 8.14.0
gyp verb ensuring nodedir is created /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp/8.14.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.14.0' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.14.0
gyp verb remove removing development files for version: 8.14.0
gyp WARN install got an error, rolling back install
gyp verb command remove [ '8.14.0' ]
gyp verb remove using node-gyp dir: /usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp
gyp verb remove removing target version: 8.14.0
gyp verb remove removing development files for version: 8.14.0
gyp ERR! configure error
gyp ERR! stack Error: EACCES: permission denied, mkdir '/usr/lib/node_modules/@angular/cli/node_modules/node-sass/.node-gyp'
gyp ERR! System Linux 3.10.0-862.14.4.el7.x86_64
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/@angular/cli/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /usr/lib/node_modules/@angular/cli/node_modules/node-sass
gyp ERR! node -v v8.14.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1

> serverless@1.30.0 postinstall /usr/lib/node_modules/serverless
> node ./scripts/postinstall.js


┌───────────────────────────────────────────────────┐
│          serverless update check failed           │
│        Try running with sudo or get access        │
│       to the local update config store via        │
│ sudo chown -R $USER:$(id -gn $USER) /root/.config │
└───────────────────────────────────────────────────┘
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules/@angular/cli/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 (node_modules/jshint/node_modules/phantomjs-prebuilt):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: phantomjs-prebuilt@2.1.16 install: `node install.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 (node_modules/@angular/cli/node_modules/node-sass):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: node-sass@4.10.0 postinstall: `node scripts/build.js`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

+ jshint@2.9.6
+ serverless@1.30.0
+ @angular/cli@1.7.3
added 1287 packages from 813 contributors in 46.945s
Removing intermediate container d8eaf577ddb8
 ---> 71105abb92f0
Step 7/16 : COPY dockerfiles/jenkins-ce/plugins.txt /usr/share/jenkins/ref/plugins.txt
```

**Comment by bleggett** [comment]
Alright, got it.

- Jshint pulls in `phantomjs` _as an optional dependency_ which fails without root access
- Angular-cli pulls in `node-sass` _as an optional dependency_ which fails without root access
- and the `serverless update` postinstall hook fails, whatever that is

It just so happened that the two deps that failed were both optional dependencies, so npm will try to install them, but the core functionality of the package should still work if they are not present.

**Comment by suryajak** [comment]
Since it is not a hotfix anymore, I have changed the base to a new branch so that we can validate as part of our build process and then merge to `master`.

**Comment by bleggett** [comment]
@suryajak I'd rather wait for the fixes in `jenkins_docker` to hit, seems a waste to go thru the rigamarole of creating a separate test branch for this.

**Pull request merged**
