### PR TITLE
Fix the issue with /tmp/jazz-chef overwrite

### PR DESCRIPTION
**Pull request by rajeevr2715**
Destroy the /tmp/jazz-chef directory in the terraform destroy.

### CODE REVIEW

**Comment by bleggett** [comment]
This is harmless enough, though it should not be necessary if the Chef scripts are overwriting stuff correctly.

What specific error did you guys get that this fixed?

**Comment by rajeevr2715** [comment]
@bleggett  See the error details below,

> [0m[0mnull_resource.chef_provision_jenkins_server (remote-exec): Connected!
> [0m[1mnull_resource.chef_provision_jenkins_server: Provisioning with 'file'...[0m[0m
> [0m[1mnull_resource.chef_provision_jenkins_server: Provisioning with 'file'...[0m[0m
> [31m
> [1m[31mError: [0m[0m[1mError applying plan:
> 
> 1 error(s) occurred:
> 
> * null_resource.chef_provision_jenkins_server: Upload failed: Process exited with status 1

**Comment by bleggett** [comment]
@rajeevr2715 Hmm ok, I thought the Terraform `file` provisioner would overwrite but I guess not.

It seems like a good idea to clean up after ourselves anyway, that directory can get rather large.

That being said, is there a reason we can't just delete that directory right after the Chef provisioner finishes, rather than triggering on `tf destroy`? 

The only thing that might need to be left there during normal operation is the `jazz-core` repo, the rest of that directory's contents can be deleted safely after Chef finishes.

**Comment by rajeevr2715** [comment]
@bleggett I think that is also fine, but I did not tested it. I have tested only the terraform destroy and found it is working. One thing I would say keeping the files will help us to debug if in case (at least in develop mode).

**Comment by bleggett** [comment]
@rajeevr2715 Yeah, the problem is since we run `tf destroy` on failure, any failure in the Chef scripts will fail the Terraform step, which will result in the Chef scripts being removed from the box before we can SSH in to debug them.

So I would at least like to leave the Chef scripts out there for debugging if the installer fails, versus removing it during destroy.

**Pull request merged**
