### PR TITLE
Support a list of AWS Services as event sources for AWS Lambda functions

### PR DESCRIPTION
**Pull request by suryajak**
### Description of the Change

Support event sources - Kinesis, DynamoDB Streams, SQS.  Scheduled Events are already supported.

### Benefits

Developers will now be able to select specific AWS services (Kinesis, DynamoDB Streams, SQS) as event sources for their functions (AWS Lambda).

### Possible Drawbacks

None

### Applicable Issues

None

### CODE REVIEW

**Comment by suryajak** [comment]
@bleggett : One of the tests is failing: "The command "test/check-bash.sh" exited with 1.". Can you advise if we this is a go/no-go for the `events` release?

**Comment by bleggett** [comment]
There is a valid linting issue with that file in both `master` and `events`, but Travis is restricting itself to _only_ the commits in the PR for some reason, it's not including the commit range I expected in `$TRAVIS_COMMIT_RANGE` (one would assume, and the docs state, that this would give you the range of commits covered by the PR, but it [seems that is not the case](https://github.com/travis-ci/travis-ci/issues/4596))

So that file has linting errors, but the problem exists in `master` too, so this should not hold up the release.

**Comment by bleggett** [comment]
Fixed this Travis quirk in `master`, checks should limit themselves to the commit range in the PR.

**Comment by suryajak** [comment]
Merging this branch as the functionality is working except for the following cases:

- https://github.com/tmobile/jazz/projects/2#card-13622251
- https://github.com/tmobile/jazz/projects/2#card-13622293

We will make a release once the above are fixed.

**Pull request merged**
